### ISSUE TITLE
Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by VishaliOSRapidops** [RadiusNetworks/flybuy-ios-example#3]
**What did you do?**
I have installed the Xcode 12GM.

**What did you expect to happen?**
My app compiled without problems.

**What happened instead?**
I got the compilation error:
Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler.

**Comment by ajhewitt** [comment]
Updated iOS SDK pending release. Will update example app and confirm fix.
